# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  displayName: 'Maven $(System.DefaultWorkingDirectory)/_VenkataMaredla_demo-java11-CF/pom.xml'
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/_VenkataMaredla_demo-java11-CF/pom.xml'
    publishJUnitResults: false

- task: ms-vsts.cloud-foundry-build-extension.cloud-foundry-cli-install-task.CloudFoundryCLIInstall@0
  displayName: 'Install Cloud Foundry CLI 6.43.0'

- task: ms-vsts.cloud-foundry-build-extension.cloud-foundry-task.CloudFoundry@1
  displayName: 'Push to Cloud Foundry'
  inputs:
    cfEndpoint: cflogin
    cfManifest: '$(Build.SourcesDirectory)/_VenkataMaredla_demo-java11-CF/manifest.yml'

